name: Test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v2
      - name: "Set up JDK 8"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Build with gradle
        run: ./gradlew shadowJar
      - name: Build docker image and deploy to docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hsldevcom/transitlog-passenger-count
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
